/** Official TFF Nesine 3. Lig 02 2026-2027 pairings and published scores (captured 2026-09-15). */
export const TFF_GROUP2_SOURCE = `
1.Hafta
BURSA YILDIRIM SPOR KULÜBÜ | 1 - 0 | SÖKE 1970 SPOR KULÜBÜ
BİGASPOR | 1 - 1 | UŞAK SPOR A.Ş.
1922 AKŞEHİR SPOR KULÜBÜ | 0 - 4 | GEMLİK SÜMERBEY FUTBOL SPOR A.Ş.
ETİMESGUT SPOR KULÜBÜ | 1 - 0 | KARŞIYAKA
ESKİŞEHİRSPOR KULÜBÜ | 4 - 0 | ALANYA 1221 FUTBOL SPOR KULÜBÜ
KEPEZ SPOR FUTBOL A.Ş. | 0 - 2 | ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş.
BALIKESİRSPOR | 4 - 1 | BUCASPOR 1928
GAZİEMİR G.O.G. SPOR YAT. A.Ş. | 0 - 3 | AYVALIKGÜCÜ BELEDİYESPOR
ALTAY | 1 - 1 | DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ
2.Hafta
AYVALIKGÜCÜ BELEDİYESPOR | 4 - 1 | KEPEZ SPOR FUTBOL A.Ş.
SÖKE 1970 SPOR KULÜBÜ | 2 - 0 | GAZİEMİR G.O.G. SPOR YAT. A.Ş.
KARŞIYAKA | 1 - 1 | ALTAY
ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş. | 2 - 2 | BİGASPOR
BUCASPOR 1928 | 2 - 1 | 1922 AKŞEHİR SPOR KULÜBÜ
GEMLİK SÜMERBEY FUTBOL SPOR A.Ş. | 1 - 0 | ETİMESGUT SPOR KULÜBÜ
ALANYA 1221 FUTBOL SPOR KULÜBÜ | 0 - 3 | BALIKESİRSPOR
UŞAK SPOR A.Ş. | 2 - 2 | ESKİŞEHİRSPOR KULÜBÜ
DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ | 0 - 2 | BURSA YILDIRIM SPOR KULÜBÜ
3.Hafta
BİGASPOR | - | ESKİŞEHİRSPOR KULÜBÜ
1922 AKŞEHİR SPOR KULÜBÜ | - | ALANYA 1221 FUTBOL SPOR KULÜBÜ
BURSA YILDIRIM SPOR KULÜBÜ | - | KARŞIYAKA
BALIKESİRSPOR | - | UŞAK SPOR A.Ş.
ETİMESGUT SPOR KULÜBÜ | - | BUCASPOR 1928
KEPEZ SPOR FUTBOL A.Ş. | - | SÖKE 1970 SPOR KULÜBÜ
ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş. | - | AYVALIKGÜCÜ BELEDİYESPOR
GAZİEMİR G.O.G. SPOR YAT. A.Ş. | - | DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ
ALTAY | - | GEMLİK SÜMERBEY FUTBOL SPOR A.Ş.
4.Hafta
KARŞIYAKA | - | GAZİEMİR G.O.G. SPOR YAT. A.Ş.
AYVALIKGÜCÜ BELEDİYESPOR | - | BİGASPOR
ALANYA 1221 FUTBOL SPOR KULÜBÜ | - | ETİMESGUT SPOR KULÜBÜ
SÖKE 1970 SPOR KULÜBÜ | - | ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş.
UŞAK SPOR A.Ş. | - | 1922 AKŞEHİR SPOR KULÜBÜ
ESKİŞEHİRSPOR KULÜBÜ | - | BALIKESİRSPOR
BUCASPOR 1928 | - | ALTAY
DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ | - | KEPEZ SPOR FUTBOL A.Ş.
GEMLİK SÜMERBEY FUTBOL SPOR A.Ş. | - | BURSA YILDIRIM SPOR KULÜBÜ
5.Hafta
ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş. | - | DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ
BİGASPOR | - | BALIKESİRSPOR
1922 AKŞEHİR SPOR KULÜBÜ | - | ESKİŞEHİRSPOR KULÜBÜ
GAZİEMİR G.O.G. SPOR YAT. A.Ş. | - | GEMLİK SÜMERBEY FUTBOL SPOR A.Ş.
AYVALIKGÜCÜ BELEDİYESPOR | - | SÖKE 1970 SPOR KULÜBÜ
BURSA YILDIRIM SPOR KULÜBÜ | - | BUCASPOR 1928
ETİMESGUT SPOR KULÜBÜ | - | UŞAK SPOR A.Ş.
KEPEZ SPOR FUTBOL A.Ş. | - | KARŞIYAKA
ALTAY | - | ALANYA 1221 FUTBOL SPOR KULÜBÜ
6.Hafta
KARŞIYAKA | - | ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş.
ESKİŞEHİRSPOR KULÜBÜ | - | ETİMESGUT SPOR KULÜBÜ
BALIKESİRSPOR | - | 1922 AKŞEHİR SPOR KULÜBÜ
DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ | - | AYVALIKGÜCÜ BELEDİYESPOR
SÖKE 1970 SPOR KULÜBÜ | - | BİGASPOR
GEMLİK SÜMERBEY FUTBOL SPOR A.Ş. | - | KEPEZ SPOR FUTBOL A.Ş.
UŞAK SPOR A.Ş. | - | ALTAY
BUCASPOR 1928 | - | GAZİEMİR G.O.G. SPOR YAT. A.Ş.
ALANYA 1221 FUTBOL SPOR KULÜBÜ | - | BURSA YILDIRIM SPOR KULÜBÜ
7.Hafta
ALTAY | - | ESKİŞEHİRSPOR KULÜBÜ
ETİMESGUT SPOR KULÜBÜ | - | BALIKESİRSPOR
SÖKE 1970 SPOR KULÜBÜ | - | DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ
BİGASPOR | - | 1922 AKŞEHİR SPOR KULÜBÜ
BURSA YILDIRIM SPOR KULÜBÜ | - | UŞAK SPOR A.Ş.
KEPEZ SPOR FUTBOL A.Ş. | - | BUCASPOR 1928
GAZİEMİR G.O.G. SPOR YAT. A.Ş. | - | ALANYA 1221 FUTBOL SPOR KULÜBÜ
AYVALIKGÜCÜ BELEDİYESPOR | - | KARŞIYAKA
ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş. | - | GEMLİK SÜMERBEY FUTBOL SPOR A.Ş.
8.Hafta
ESKİŞEHİRSPOR KULÜBÜ | - | BURSA YILDIRIM SPOR KULÜBÜ
BUCASPOR 1928 | - | ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş.
KARŞIYAKA | - | SÖKE 1970 SPOR KULÜBÜ
1922 AKŞEHİR SPOR KULÜBÜ | - | ETİMESGUT SPOR KULÜBÜ
ALANYA 1221 FUTBOL SPOR KULÜBÜ | - | KEPEZ SPOR FUTBOL A.Ş.
UŞAK SPOR A.Ş. | - | GAZİEMİR G.O.G. SPOR YAT. A.Ş.
BALIKESİRSPOR | - | ALTAY
DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ | - | BİGASPOR
GEMLİK SÜMERBEY FUTBOL SPOR A.Ş. | - | AYVALIKGÜCÜ BELEDİYESPOR
9.Hafta
GAZİEMİR G.O.G. SPOR YAT. A.Ş. | - | ESKİŞEHİRSPOR KULÜBÜ
BURSA YILDIRIM SPOR KULÜBÜ | - | BALIKESİRSPOR
AYVALIKGÜCÜ BELEDİYESPOR | - | BUCASPOR 1928
KEPEZ SPOR FUTBOL A.Ş. | - | UŞAK SPOR A.Ş.
SÖKE 1970 SPOR KULÜBÜ | - | GEMLİK SÜMERBEY FUTBOL SPOR A.Ş.
ALTAY | - | 1922 AKŞEHİR SPOR KULÜBÜ
BİGASPOR | - | ETİMESGUT SPOR KULÜBÜ
DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ | - | KARŞIYAKA
ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş. | - | ALANYA 1221 FUTBOL SPOR KULÜBÜ
10.Hafta
UŞAK SPOR A.Ş. | - | ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş.
BUCASPOR 1928 | - | SÖKE 1970 SPOR KULÜBÜ
KARŞIYAKA | - | BİGASPOR
ALANYA 1221 FUTBOL SPOR KULÜBÜ | - | AYVALIKGÜCÜ BELEDİYESPOR
ETİMESGUT SPOR KULÜBÜ | - | ALTAY
BALIKESİRSPOR | - | GAZİEMİR G.O.G. SPOR YAT. A.Ş.
GEMLİK SÜMERBEY FUTBOL SPOR A.Ş. | - | DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ
ESKİŞEHİRSPOR KULÜBÜ | - | KEPEZ SPOR FUTBOL A.Ş.
1922 AKŞEHİR SPOR KULÜBÜ | - | BURSA YILDIRIM SPOR KULÜBÜ
11.Hafta
KARŞIYAKA | - | GEMLİK SÜMERBEY FUTBOL SPOR A.Ş.
BİGASPOR | - | ALTAY
ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş. | - | ESKİŞEHİRSPOR KULÜBÜ
KEPEZ SPOR FUTBOL A.Ş. | - | BALIKESİRSPOR
GAZİEMİR G.O.G. SPOR YAT. A.Ş. | - | 1922 AKŞEHİR SPOR KULÜBÜ
AYVALIKGÜCÜ BELEDİYESPOR | - | UŞAK SPOR A.Ş.
DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ | - | BUCASPOR 1928
BURSA YILDIRIM SPOR KULÜBÜ | - | ETİMESGUT SPOR KULÜBÜ
SÖKE 1970 SPOR KULÜBÜ | - | ALANYA 1221 FUTBOL SPOR KULÜBÜ
12.Hafta
BUCASPOR 1928 | - | KARŞIYAKA
BALIKESİRSPOR | - | ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş.
UŞAK SPOR A.Ş. | - | SÖKE 1970 SPOR KULÜBÜ
GEMLİK SÜMERBEY FUTBOL SPOR A.Ş. | - | BİGASPOR
ESKİŞEHİRSPOR KULÜBÜ | - | AYVALIKGÜCÜ BELEDİYESPOR
ETİMESGUT SPOR KULÜBÜ | - | GAZİEMİR G.O.G. SPOR YAT. A.Ş.
ALANYA 1221 FUTBOL SPOR KULÜBÜ | - | DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ
1922 AKŞEHİR SPOR KULÜBÜ | - | KEPEZ SPOR FUTBOL A.Ş.
ALTAY | - | BURSA YILDIRIM SPOR KULÜBÜ
13.Hafta
GAZİEMİR G.O.G. SPOR YAT. A.Ş. | - | ALTAY
GEMLİK SÜMERBEY FUTBOL SPOR A.Ş. | - | BUCASPOR 1928
KEPEZ SPOR FUTBOL A.Ş. | - | ETİMESGUT SPOR KULÜBÜ
KARŞIYAKA | - | ALANYA 1221 FUTBOL SPOR KULÜBÜ
DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ | - | UŞAK SPOR A.Ş.
ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş. | - | 1922 AKŞEHİR SPOR KULÜBÜ
SÖKE 1970 SPOR KULÜBÜ | - | ESKİŞEHİRSPOR KULÜBÜ
AYVALIKGÜCÜ BELEDİYESPOR | - | BALIKESİRSPOR
BİGASPOR | - | BURSA YILDIRIM SPOR KULÜBÜ
14.Hafta
BUCASPOR 1928 | - | BİGASPOR
1922 AKŞEHİR SPOR KULÜBÜ | - | AYVALIKGÜCÜ BELEDİYESPOR
BURSA YILDIRIM SPOR KULÜBÜ | - | GAZİEMİR G.O.G. SPOR YAT. A.Ş.
ESKİŞEHİRSPOR KULÜBÜ | - | DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ
ALTAY | - | KEPEZ SPOR FUTBOL A.Ş.
BALIKESİRSPOR | - | SÖKE 1970 SPOR KULÜBÜ
UŞAK SPOR A.Ş. | - | KARŞIYAKA
ETİMESGUT SPOR KULÜBÜ | - | ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş.
ALANYA 1221 FUTBOL SPOR KULÜBÜ | - | GEMLİK SÜMERBEY FUTBOL SPOR A.Ş.
15.Hafta
SÖKE 1970 SPOR KULÜBÜ | - | 1922 AKŞEHİR SPOR KULÜBÜ
ALANYA 1221 FUTBOL SPOR KULÜBÜ | - | BUCASPOR 1928
GAZİEMİR G.O.G. SPOR YAT. A.Ş. | - | BİGASPOR
DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ | - | BALIKESİRSPOR
KARŞIYAKA | - | ESKİŞEHİRSPOR KULÜBÜ
ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş. | - | ALTAY
GEMLİK SÜMERBEY FUTBOL SPOR A.Ş. | - | UŞAK SPOR A.Ş.
AYVALIKGÜCÜ BELEDİYESPOR | - | ETİMESGUT SPOR KULÜBÜ
KEPEZ SPOR FUTBOL A.Ş. | - | BURSA YILDIRIM SPOR KULÜBÜ
16.Hafta
BURSA YILDIRIM SPOR KULÜBÜ | - | ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş.
ETİMESGUT SPOR KULÜBÜ | - | SÖKE 1970 SPOR KULÜBÜ
ALTAY | - | AYVALIKGÜCÜ BELEDİYESPOR
1922 AKŞEHİR SPOR KULÜBÜ | - | DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ
GAZİEMİR G.O.G. SPOR YAT. A.Ş. | - | KEPEZ SPOR FUTBOL A.Ş.
UŞAK SPOR A.Ş. | - | BUCASPOR 1928
BİGASPOR | - | ALANYA 1221 FUTBOL SPOR KULÜBÜ
BALIKESİRSPOR | - | KARŞIYAKA
ESKİŞEHİRSPOR KULÜBÜ | - | GEMLİK SÜMERBEY FUTBOL SPOR A.Ş.
17.Hafta
DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ | - | ETİMESGUT SPOR KULÜBÜ
SÖKE 1970 SPOR KULÜBÜ | - | ALTAY
KEPEZ SPOR FUTBOL A.Ş. | - | BİGASPOR
GEMLİK SÜMERBEY FUTBOL SPOR A.Ş. | - | BALIKESİRSPOR
BUCASPOR 1928 | - | ESKİŞEHİRSPOR KULÜBÜ
ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş. | - | GAZİEMİR G.O.G. SPOR YAT. A.Ş.
ALANYA 1221 FUTBOL SPOR KULÜBÜ | - | UŞAK SPOR A.Ş.
KARŞIYAKA | - | 1922 AKŞEHİR SPOR KULÜBÜ
AYVALIKGÜCÜ BELEDİYESPOR | - | BURSA YILDIRIM SPOR KULÜBÜ
18.Hafta
SÖKE 1970 SPOR KULÜBÜ | - | BURSA YILDIRIM SPOR KULÜBÜ
GEMLİK SÜMERBEY FUTBOL SPOR A.Ş. | - | 1922 AKŞEHİR SPOR KULÜBÜ
KARŞIYAKA | - | ETİMESGUT SPOR KULÜBÜ
AYVALIKGÜCÜ BELEDİYESPOR | - | GAZİEMİR G.O.G. SPOR YAT. A.Ş.
DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ | - | ALTAY
ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş. | - | KEPEZ SPOR FUTBOL A.Ş.
ALANYA 1221 FUTBOL SPOR KULÜBÜ | - | ESKİŞEHİRSPOR KULÜBÜ
BUCASPOR 1928 | - | BALIKESİRSPOR
UŞAK SPOR A.Ş. | - | BİGASPOR
19.Hafta
KEPEZ SPOR FUTBOL A.Ş. | - | AYVALIKGÜCÜ BELEDİYESPOR
BURSA YILDIRIM SPOR KULÜBÜ | - | DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ
BİGASPOR | - | ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş.
ALTAY | - | KARŞIYAKA
BALIKESİRSPOR | - | ALANYA 1221 FUTBOL SPOR KULÜBÜ
ESKİŞEHİRSPOR KULÜBÜ | - | UŞAK SPOR A.Ş.
1922 AKŞEHİR SPOR KULÜBÜ | - | BUCASPOR 1928
GAZİEMİR G.O.G. SPOR YAT. A.Ş. | - | SÖKE 1970 SPOR KULÜBÜ
ETİMESGUT SPOR KULÜBÜ | - | GEMLİK SÜMERBEY FUTBOL SPOR A.Ş.
20.Hafta
KARŞIYAKA | - | BURSA YILDIRIM SPOR KULÜBÜ
ALANYA 1221 FUTBOL SPOR KULÜBÜ | - | 1922 AKŞEHİR SPOR KULÜBÜ
AYVALIKGÜCÜ BELEDİYESPOR | - | ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş.
BUCASPOR 1928 | - | ETİMESGUT SPOR KULÜBÜ
DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ | - | GAZİEMİR G.O.G. SPOR YAT. A.Ş.
SÖKE 1970 SPOR KULÜBÜ | - | KEPEZ SPOR FUTBOL A.Ş.
GEMLİK SÜMERBEY FUTBOL SPOR A.Ş. | - | ALTAY
UŞAK SPOR A.Ş. | - | BALIKESİRSPOR
ESKİŞEHİRSPOR KULÜBÜ | - | BİGASPOR
21.Hafta
BİGASPOR | - | AYVALIKGÜCÜ BELEDİYESPOR
BALIKESİRSPOR | - | ESKİŞEHİRSPOR KULÜBÜ
KEPEZ SPOR FUTBOL A.Ş. | - | DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ
ETİMESGUT SPOR KULÜBÜ | - | ALANYA 1221 FUTBOL SPOR KULÜBÜ
GAZİEMİR G.O.G. SPOR YAT. A.Ş. | - | KARŞIYAKA
ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş. | - | SÖKE 1970 SPOR KULÜBÜ
BURSA YILDIRIM SPOR KULÜBÜ | - | GEMLİK SÜMERBEY FUTBOL SPOR A.Ş.
1922 AKŞEHİR SPOR KULÜBÜ | - | UŞAK SPOR A.Ş.
ALTAY | - | BUCASPOR 1928
22.Hafta
ESKİŞEHİRSPOR KULÜBÜ | - | 1922 AKŞEHİR SPOR KULÜBÜ
UŞAK SPOR A.Ş. | - | ETİMESGUT SPOR KULÜBÜ
DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ | - | ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş.
KARŞIYAKA | - | KEPEZ SPOR FUTBOL A.Ş.
ALANYA 1221 FUTBOL SPOR KULÜBÜ | - | ALTAY
GEMLİK SÜMERBEY FUTBOL SPOR A.Ş. | - | GAZİEMİR G.O.G. SPOR YAT. A.Ş.
SÖKE 1970 SPOR KULÜBÜ | - | AYVALIKGÜCÜ BELEDİYESPOR
BALIKESİRSPOR | - | BİGASPOR
BUCASPOR 1928 | - | BURSA YILDIRIM SPOR KULÜBÜ
23.Hafta
KEPEZ SPOR FUTBOL A.Ş. | - | GEMLİK SÜMERBEY FUTBOL SPOR A.Ş.
1922 AKŞEHİR SPOR KULÜBÜ | - | BALIKESİRSPOR
ETİMESGUT SPOR KULÜBÜ | - | ESKİŞEHİRSPOR KULÜBÜ
AYVALIKGÜCÜ BELEDİYESPOR | - | DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ
BURSA YILDIRIM SPOR KULÜBÜ | - | ALANYA 1221 FUTBOL SPOR KULÜBÜ
ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş. | - | KARŞIYAKA
BİGASPOR | - | SÖKE 1970 SPOR KULÜBÜ
GAZİEMİR G.O.G. SPOR YAT. A.Ş. | - | BUCASPOR 1928
ALTAY | - | UŞAK SPOR A.Ş.
24.Hafta
DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ | - | SÖKE 1970 SPOR KULÜBÜ
GEMLİK SÜMERBEY FUTBOL SPOR A.Ş. | - | ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş.
BALIKESİRSPOR | - | ETİMESGUT SPOR KULÜBÜ
BUCASPOR 1928 | - | KEPEZ SPOR FUTBOL A.Ş.
ALANYA 1221 FUTBOL SPOR KULÜBÜ | - | GAZİEMİR G.O.G. SPOR YAT. A.Ş.
ESKİŞEHİRSPOR KULÜBÜ | - | ALTAY
KARŞIYAKA | - | AYVALIKGÜCÜ BELEDİYESPOR
1922 AKŞEHİR SPOR KULÜBÜ | - | BİGASPOR
UŞAK SPOR A.Ş. | - | BURSA YILDIRIM SPOR KULÜBÜ
25.Hafta
AYVALIKGÜCÜ BELEDİYESPOR | - | GEMLİK SÜMERBEY FUTBOL SPOR A.Ş.
ALTAY | - | BALIKESİRSPOR
BURSA YILDIRIM SPOR KULÜBÜ | - | ESKİŞEHİRSPOR KULÜBÜ
BİGASPOR | - | DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ
KEPEZ SPOR FUTBOL A.Ş. | - | ALANYA 1221 FUTBOL SPOR KULÜBÜ
SÖKE 1970 SPOR KULÜBÜ | - | KARŞIYAKA
ETİMESGUT SPOR KULÜBÜ | - | 1922 AKŞEHİR SPOR KULÜBÜ
GAZİEMİR G.O.G. SPOR YAT. A.Ş. | - | UŞAK SPOR A.Ş.
ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş. | - | BUCASPOR 1928
26.Hafta
GEMLİK SÜMERBEY FUTBOL SPOR A.Ş. | - | SÖKE 1970 SPOR KULÜBÜ
ALANYA 1221 FUTBOL SPOR KULÜBÜ | - | ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş.
ESKİŞEHİRSPOR KULÜBÜ | - | GAZİEMİR G.O.G. SPOR YAT. A.Ş.
1922 AKŞEHİR SPOR KULÜBÜ | - | ALTAY
UŞAK SPOR A.Ş. | - | KEPEZ SPOR FUTBOL A.Ş.
KARŞIYAKA | - | DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ
BUCASPOR 1928 | - | AYVALIKGÜCÜ BELEDİYESPOR
ETİMESGUT SPOR KULÜBÜ | - | BİGASPOR
BALIKESİRSPOR | - | BURSA YILDIRIM SPOR KULÜBÜ
27.Hafta
DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ | - | GEMLİK SÜMERBEY FUTBOL SPOR A.Ş.
GAZİEMİR G.O.G. SPOR YAT. A.Ş. | - | BALIKESİRSPOR
KEPEZ SPOR FUTBOL A.Ş. | - | ESKİŞEHİRSPOR KULÜBÜ
ALTAY | - | ETİMESGUT SPOR KULÜBÜ
BİGASPOR | - | KARŞIYAKA
AYVALIKGÜCÜ BELEDİYESPOR | - | ALANYA 1221 FUTBOL SPOR KULÜBÜ
SÖKE 1970 SPOR KULÜBÜ | - | BUCASPOR 1928
ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş. | - | UŞAK SPOR A.Ş.
BURSA YILDIRIM SPOR KULÜBÜ | - | 1922 AKŞEHİR SPOR KULÜBÜ
28.Hafta
ALANYA 1221 FUTBOL SPOR KULÜBÜ | - | SÖKE 1970 SPOR KULÜBÜ
GEMLİK SÜMERBEY FUTBOL SPOR A.Ş. | - | KARŞIYAKA
ESKİŞEHİRSPOR KULÜBÜ | - | ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş.
UŞAK SPOR A.Ş. | - | AYVALIKGÜCÜ BELEDİYESPOR
ALTAY | - | BİGASPOR
BUCASPOR 1928 | - | DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ
BALIKESİRSPOR | - | KEPEZ SPOR FUTBOL A.Ş.
1922 AKŞEHİR SPOR KULÜBÜ | - | GAZİEMİR G.O.G. SPOR YAT. A.Ş.
ETİMESGUT SPOR KULÜBÜ | - | BURSA YILDIRIM SPOR KULÜBÜ
29.Hafta
BİGASPOR | - | GEMLİK SÜMERBEY FUTBOL SPOR A.Ş.
BURSA YILDIRIM SPOR KULÜBÜ | - | ALTAY
ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş. | - | BALIKESİRSPOR
AYVALIKGÜCÜ BELEDİYESPOR | - | ESKİŞEHİRSPOR KULÜBÜ
GAZİEMİR G.O.G. SPOR YAT. A.Ş. | - | ETİMESGUT SPOR KULÜBÜ
DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ | - | ALANYA 1221 FUTBOL SPOR KULÜBÜ
KEPEZ SPOR FUTBOL A.Ş. | - | 1922 AKŞEHİR SPOR KULÜBÜ
KARŞIYAKA | - | BUCASPOR 1928
SÖKE 1970 SPOR KULÜBÜ | - | UŞAK SPOR A.Ş.
30.Hafta
ESKİŞEHİRSPOR KULÜBÜ | - | SÖKE 1970 SPOR KULÜBÜ
1922 AKŞEHİR SPOR KULÜBÜ | - | ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş.
ALANYA 1221 FUTBOL SPOR KULÜBÜ | - | KARŞIYAKA
BALIKESİRSPOR | - | AYVALIKGÜCÜ BELEDİYESPOR
BURSA YILDIRIM SPOR KULÜBÜ | - | BİGASPOR
UŞAK SPOR A.Ş. | - | DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ
ALTAY | - | GAZİEMİR G.O.G. SPOR YAT. A.Ş.
ETİMESGUT SPOR KULÜBÜ | - | KEPEZ SPOR FUTBOL A.Ş.
BUCASPOR 1928 | - | GEMLİK SÜMERBEY FUTBOL SPOR A.Ş.
31.Hafta
GAZİEMİR G.O.G. SPOR YAT. A.Ş. | - | BURSA YILDIRIM SPOR KULÜBÜ
KEPEZ SPOR FUTBOL A.Ş. | - | ALTAY
SÖKE 1970 SPOR KULÜBÜ | - | BALIKESİRSPOR
DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ | - | ESKİŞEHİRSPOR KULÜBÜ
GEMLİK SÜMERBEY FUTBOL SPOR A.Ş. | - | ALANYA 1221 FUTBOL SPOR KULÜBÜ
ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş. | - | ETİMESGUT SPOR KULÜBÜ
BİGASPOR | - | BUCASPOR 1928
AYVALIKGÜCÜ BELEDİYESPOR | - | 1922 AKŞEHİR SPOR KULÜBÜ
KARŞIYAKA | - | UŞAK SPOR A.Ş.
32.Hafta
1922 AKŞEHİR SPOR KULÜBÜ | - | SÖKE 1970 SPOR KULÜBÜ
UŞAK SPOR A.Ş. | - | GEMLİK SÜMERBEY FUTBOL SPOR A.Ş.
ALTAY | - | ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş.
ESKİŞEHİRSPOR KULÜBÜ | - | KARŞIYAKA
BUCASPOR 1928 | - | ALANYA 1221 FUTBOL SPOR KULÜBÜ
ETİMESGUT SPOR KULÜBÜ | - | AYVALIKGÜCÜ BELEDİYESPOR
BİGASPOR | - | GAZİEMİR G.O.G. SPOR YAT. A.Ş.
BURSA YILDIRIM SPOR KULÜBÜ | - | KEPEZ SPOR FUTBOL A.Ş.
BALIKESİRSPOR | - | DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ
33.Hafta
KEPEZ SPOR FUTBOL A.Ş. | - | GAZİEMİR G.O.G. SPOR YAT. A.Ş.
AYVALIKGÜCÜ BELEDİYESPOR | - | ALTAY
GEMLİK SÜMERBEY FUTBOL SPOR A.Ş. | - | ESKİŞEHİRSPOR KULÜBÜ
ALANYA 1221 FUTBOL SPOR KULÜBÜ | - | BİGASPOR
KARŞIYAKA | - | BALIKESİRSPOR
SÖKE 1970 SPOR KULÜBÜ | - | ETİMESGUT SPOR KULÜBÜ
DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ | - | 1922 AKŞEHİR SPOR KULÜBÜ
BUCASPOR 1928 | - | UŞAK SPOR A.Ş.
ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş. | - | BURSA YILDIRIM SPOR KULÜBÜ
34.Hafta
BALIKESİRSPOR | - | GEMLİK SÜMERBEY FUTBOL SPOR A.Ş.
ALTAY | - | SÖKE 1970 SPOR KULÜBÜ
ESKİŞEHİRSPOR KULÜBÜ | - | BUCASPOR 1928
GAZİEMİR G.O.G. SPOR YAT. A.Ş. | - | ESKİŞEHİR ANADOLU SPOR FAALİYETLERİ A.Ş.
UŞAK SPOR A.Ş. | - | ALANYA 1221 FUTBOL SPOR KULÜBÜ
BURSA YILDIRIM SPOR KULÜBÜ | - | AYVALIKGÜCÜ BELEDİYESPOR
1922 AKŞEHİR SPOR KULÜBÜ | - | KARŞIYAKA
BİGASPOR | - | KEPEZ SPOR FUTBOL A.Ş.
ETİMESGUT SPOR KULÜBÜ | - | DENİZLİ İDMANYURDU 1959 SPOR KULÜBÜ
`.trim();
